# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "AGRESSIVE LIBERTARIANS: Not Iniating, But Fighting Back"
email: doughiltz1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Exploring strategies for resisting, progressivism, socialism and government in
  general.  Small government types are welcome to the conversation.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.agressivelibertarians.com/" # the base hostname & protocol for your site
twitter_username: dooglehiltz
github_username:  dooglehiltz

# Build settings
markdown: kramdown
